subdir-ccflags-y += -Werror
ccflags-y += -I$(srctree)/drivers/misc/mediatek/include/mt-plat/
ccflags-y += -I$(srctree)/drivers/input/misc/mediatek
# In case the platform does NOT support this type of sensors

obj-$(CONFIG_INPUT_SX9310)	+=  sar_sensor/
